[project]
name = "rag-stress-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "commitizen>=4.13.2",
]
